# Generated by Django 3.2.2 on 2021-05-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('background', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DaySensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'monday'), ('Tue', 'tuesday'), ('Wed', 'wednesday'), ('Thu', 'thursday'), ('Fri', 'friday'), ('Sat', 'saturday'), ('Sun', 'sunday')], max_length=3)),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=30)),
                ('gym_address', models.CharField(max_length=80)),
                ('gym_limitation', models.IntegerField(default=0)),
                ('gym_coordinate_lat', models.FloatField()),
                ('gym_coordinate_long', models.FloatField()),
                ('gym_class', models.CharField(max_length=40)),
                ('gym_start', models.TextField()),
                ('gym_close', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=30)),
                ('park_address', models.CharField(max_length=80)),
                ('park_coordinate_lat', models.FloatField()),
                ('park_coordinate_long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playground_name', models.CharField(max_length=30)),
                ('playground_address', models.CharField(max_length=80)),
                ('playground_coordinate_lat', models.FloatField()),
                ('playground_coordinate_long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SafetyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_coordinate_lat', models.FloatField()),
                ('sensor_coordinate_long', models.FloatField()),
                ('sensor_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SafeTips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='PlaygroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=10)),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.playground')),
            ],
        ),
        migrations.CreateModel(
            name='ParkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=10)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.park')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=10)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.gym')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyRoadSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('average', models.IntegerField()),
                ('day_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.daysensor')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseTips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='daysensor',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.sensor'),
        ),
    ]
