# Generated by Django 3.1.7 on 2021-04-19 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularJoggingPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('map', models.CharField(max_length=1000)),
                ('distance', models.FloatField()),
                ('elevation', models.FloatField()),
                ('background', models.CharField(max_length=50)),
                ('intruduction', models.TextField()),
                ('suburb', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('detail_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LastHourSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.sensor')),
            ],
        ),
    ]
